### ISSUE TITLE
Error when running solismod script

### ISSUE THREAD

**Issue by usbrit** [NosIreland/solismod#1]
Hi,
I have solismod installed on a Rpi zero w.

Python 3.8
solarmanv5 installed

Running the script give the following error:
```
pizero@pizero:~/solismod $ python main.py
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import config.config as config
ModuleNotFoundError: No module named 'config.config'; 'config' is not a package
```

Can anyone point me at a solution?.
Thanks

**Comment by usbrit** [comment]
I have solved this, now struggling to get Solismod to work with Pysolarmanv5

**Comment by NosIreland** [comment]
> I have solved this, now struggling to get Solismod to work with Pysolarmanv5

Are you getting any errors?

**Comment by usbrit** [comment]
No, but nothing is changing on the inverter.

Not sure what I should see to confirm Solismod and pysolarmanV5 are communicating?

**Comment by usbrit** [comment]
It looks like solismod is running OK, but don't know how to confirm:
![image](https://user-images.githubusercontent.com/53425475/191909999-0786e05d-0457-46a6-8030-1b83802fc207.png)

1. it's find pysolarmanv5
2. it's communicating with the inverter wifi stick

I can send mqtt message from HA (on another RPi) successfully

Any help appreciated.
Thanks

**Comment by usbrit** [comment]
A NodeRed Inject to mqtt gives me this:
![image](https://user-images.githubusercontent.com/53425475/191913964-219dde11-88eb-4f9b-a1ef-e6e2e568e15b.png)
But the Discharge start time doesn't change on the inverter.

How can I check the message has been received?

**Comment by NosIreland** [comment]
Looks like the message is accepted by inverter as no error is received. It could be that the charge registers on your inverter are different to mine. Try to change the time nodered/solis/minutes or nodered/solis/hours and see if inverter time changes. Unfortunately I traveling at the moment and will only be able to look into this next week.

Regards,
Andrius
________________________________

**Comment by usbrit** [comment]
Thanks!!
I got this to work!
Just need to get the correct registers identified now! Any idea where I can get a list?
Thank you

**Comment by usbrit** [comment]
I have tried to see what I can get back using a test script (based on the following from main.py):
               "nodered/solis/start_discharge_hour": [43147], "nodered/solis/start_discharge_minute": [43148],
               "nodered/solis/stop_discharge_hour": [43149], "nodered/solis/stop_discharge_minute": [43150]

`from pysolarmanv5.pysolarmanv5 import PySolarmanV5


def main():
	"""Create test file to pull data from Inverter
	"""
	modbus = PySolarmanV5(
		"192.168.X.XXX", 4XXXXXXXX2 , port=8899, mb_slave_id=1, verbose=1
		)
	print(modbus.read_holding_registers(register_addr=43147, quantity=1))
	print(modbus.read_holding_registers(register_addr=43148, quantity=1))
	print(modbus.read_holding_registers(register_addr=43149, quantity=1))
	print(modbus.read_holding_registers(register_addr=43150, quantity=1))

if __name__ == "__main__":
	main()`

![image](https://user-images.githubusercontent.com/53425475/192310344-96c51ecd-07b5-4c8d-9612-7555308cd82b.png)

This doesn't seem to tally with what my settings currently are:
![image](https://user-images.githubusercontent.com/53425475/192313487-4112ec4f-0b90-48e2-ab78-981eaee1db9d.png)

Can anyone help with register numbers for the Solis RHI-5K-48ES?
Thanks

**Comment by usbrit** [comment]
Just for interest, I check the following:

print(modbus.read_holding_registers(register_addr=43003, quantity=1)) 
	print(modbus.read_holding_registers(register_addr=43004, quantity=1))
	print(modbus.read_holding_registers(register_addr=43114, quantity=1))
	print(modbus.read_holding_registers(register_addr=43141, quantity=1))
	print(modbus.read_holding_registers(register_addr=43142, quantity=1))

and all these registers return the correct values

**Comment by NosIreland** [comment]
What firmware is your inverter running?

**Comment by usbrit** [comment]
![image](https://user-images.githubusercontent.com/53425475/192495433-e0e47383-5266-4b3b-a380-b0239caa114b.png)

Is this how to identify? Can't seem to find anything on Solis Cloud

**Comment by NosIreland** [comment]
The version is dated but it shoud still work. Your HMI is v28 and DSP ir v16. If you have 5G inverter you can ask Silis support to do OTA upgrade to later version.
You got the script reading values ok so try to modify them:

```
from pysolarmanv5.pysolarmanv5 import PySolarmanV5

def main():
"""Create test file to pull data from Inverter
"""
modbus = PySolarmanV5("192.168.X.XXX", 4XXXXXXXX2 , port=8899, mb_slave_id=1, verbose=1)

modbus.write_holding_register(register_addr=43141, value=0)
modbus.write_holding_register(register_addr=43142, value=0)

print(modbus.read_holding_registers(register_addr=43141, quantity=2))

if name == "main":
main()
```
this shoudl change the charge and discharge amps to 0. and then read the values back.

**Comment by usbrit** [comment]
Ran a modified version of that code:
`"""Create test file to pull data from Inverter"""
from pysolarmanv5.pysolarmanv5 import PySolarmanV5

def main():


	modbus = PySolarmanV5("192.168.X.XXX", 4XXXXXXXX2 , port=8899, mb_slave_id=1, verbose=1)

	modbus.write_holding_register(register_addr=43141, value=0)
	modbus.write_holding_register(register_addr=43142, value=0)

	print(modbus.read_holding_registers(register_addr=43141, quantity=2))

if __name__ == "__main__":
    main()`

and checked afterwards:
![image](https://user-images.githubusercontent.com/53425475/192563864-2053cb4b-eeb8-4b5e-866d-6eab79dc9a21.png)

43141 and 43142 have been set to 0, but...viewing the settings screen on the inverter, they don't appear to have changed. Am I looking in the right place?
![image](https://user-images.githubusercontent.com/53425475/192564809-d7b693cc-2715-49f4-ab90-4f09a5d15fea.png)

**Comment by NosIreland** [comment]
You are in the right place. Can you reboot the inverter and try again? This could be a firmware thing but lets try reboot firsts.

**Comment by usbrit** [comment]
I restarted the HMI and no change. Was this what you meant?

In the past I had tried a change of time and that worked immediately and I watch it change on the inverter https://github.com/NosIreland/solismod/issues/1#issuecomment-1256172438

**Comment by NosIreland** [comment]
HMI restart should be enough but there is no harm doing full restart. Shutdown the battery and then power off inverter.
The code is working since you can change the time. Also looking at the outputs provided the registers also seem to be the correct ones. There is something with the inverter as noted before you can ask Solis support to do firmware update as it is old.

**Comment by usbrit** [comment]
I have successfully changed settings on the inverter now after investigating Register values.

For me register 43110 is the "Charge status" but the payload is different from others (3= time charging/run and 1= time charging/stop)
I am able to change this using a python script on the pi running Solismod and PysolarmanV5 and am now working on getting HA to interface with this via MQTT.

Thanks for your help and patience, also have a ticket with Solis to get the OTA update

**Comment by NosIreland** [comment]
Nice. 
Glad to hear you got it sorted. Just a note the registers may change after the upgrade.

**Comment by mkpurcell** [comment]
@usbrit It looks like I have the same problem you had i.e. registers for charge/discharge time always return 0. Did you find the correct registers for this? I also have Solis RHI-5K-48ES, with software ver: 230013

**Comment by alienatedsec** [comment]
> I have solved this, now struggling to get Solismod to work with Pysolarmanv5

@usbrit 
How did you solve this config error?

**Comment by alienatedsec** [comment]
@NosIreland worth enabling issues section in your other repos

**Comment by NosIreland** [comment]
> @NosIreland worth enabling issues section in your other repos

I assume you refering to solismon3. I have enabled it.

**Comment by NosIreland** [comment]
Closing this as OP got it running.
